export { Navigation } from './Navigation'
export { Hero } from './Hero'
export { About } from './About'
export { Philosophy } from './Philosophy'
export { Experience } from './Experience'
export { Projects } from './Projects'
export { Writing } from './Writing'
export { Contact } from './Contact'