import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const FEED_URL = 'https://medium.com/feed/@tamarayustian';
const MAX_POSTS = 6;
const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'generated');
const OUT_FILE = join(OUT_DIR, 'medium-posts.ts');

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function decodeEntities(input) {
  return input
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x2019;/g, "'")
    .replace(/&#8217;/g, "'")
    .replace(/&#8216;/g, "'")
    .replace(/&#x2014;/g, '—')
    .replace(/&#8212;/g, '—')
    .replace(/&#8230;/g, '…')
    .replace(/&#x2026;/g, '…')
    .replace(/&#x2013;/g, '–')
    .replace(/&#8211;/g, '–');
}

function stripHtml(input) {
  return input
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<\/p>/gi, ' ')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function firstParagraph(content) {
  const match = content.match(/<p>([\s\S]*?)<\/p>/);
  if (!match) return '';
  return stripHtml(match[1]);
}

function genreFromTags(tags) {
  if (tags.some((t) => /poem|poetry/.test(t))) return 'Poem';
  if (tags.some((t) => /short-story|fiction/.test(t))) return 'Story';
  if (tags.length > 0) return 'Prose';
  return 'Essay';
}

function formatDate(pubDate) {
  const d = new Date(pubDate);
  if (Number.isNaN(d.getTime())) return '';
  return `${MONTHS[d.getMonth()]} ${d.getFullYear()}`;
}

function parseFeed(xml) {
  const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)];
  return items
    .map((m) => {
      const s = m[1];
      const titleMatch = s.match(/<title><!\[CDATA\[([\s\S]*?)\]\]><\/title>/) || s.match(/<title>([\s\S]*?)<\/title>/);
      const link = (s.match(/<link>([\s\S]*?)<\/link>/)?.[1] ?? '').split('?')[0];
      const pubDate = s.match(/<pubDate>([\s\S]*?)<\/pubDate>/)?.[1] ?? '';
      const content = s.match(/<content:encoded><!\[CDATA\[([\s\S]*?)\]\]><\/content:encoded>/)?.[1] ?? '';
      const tags = [...s.matchAll(/<category><!\[CDATA\[([\s\S]*?)\]\]><\/category>/g)].map((c) => c[1]);
      if (!titleMatch || !link) return null;
      return {
        title: decodeEntities(titleMatch[1].trim()),
        url: link,
        excerpt: decodeEntities(firstParagraph(content)),
        genre: genreFromTags(tags),
        date: formatDate(pubDate),
        rawDate: pubDate,
      };
    })
    .filter(Boolean)
    .sort((a, b) => new Date(b.rawDate).getTime() - new Date(a.rawDate).getTime())
    .slice(0, MAX_POSTS)
    .map(({ rawDate, ...post }) => post);
}

function generateModule(posts) {
  const body = JSON.stringify(posts, null, 2)
    .replace(/^\{/gm, '  {')
    .replace(/^\[/gm, '[');
  return `// AUTO-GENERATED by scripts/fetch-medium.mjs. Do not edit by hand.\n// Run \`node scripts/fetch-medium.mjs\` to refresh from ${FEED_URL}.\n\nexport type MediumPost = {\n  title: string;\n  url: string;\n  excerpt: string;\n  genre: string;\n  date: string;\n};\n\nexport const mediumPosts: MediumPost[] = ${body};\n`;
}

function writeFile(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

async function main() {
  try {
    const res = await fetch(FEED_URL, { headers: { accept: 'application/rss+xml, application/xml, text/xml, */*' } });
    if (!res.ok) throw new Error(`RSS fetch failed with status ${res.status}`);
    const xml = await res.text();
    const posts = parseFeed(xml);
    if (posts.length === 0) throw new Error('No posts parsed from RSS feed');
    writeFile(OUT_FILE, generateModule(posts));
    console.log(`fetch-medium: wrote ${posts.length} posts to ${OUT_FILE}`);
  } catch (err) {
    console.warn(`fetch-medium: ${err.message}. Keeping existing ${OUT_FILE} (if present).`);
    try {
      const existing = readFileSync(OUT_FILE, 'utf8');
      console.log(`fetch-medium: using existing file (${existing.includes('mediumPosts') ? 'valid' : 'maybe empty'})`);
    } catch {
      writeFile(OUT_FILE, generateModule([]));
      console.log('fetch-medium: no existing file; wrote empty fallback');
    }
  }
}

main();
